language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script: coverage run --source app --omit=*venv* nosetests -v

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - http://intbass.com/build/ci/travis
