language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script: nosetests --with-coverage --cover-inclusive --cover-package=app -v

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - http://intbass.com/build/ci/travis
